import { itemModel } from './item.model.js'
import { decodeFitting } from './item.decoder.js'
import { decodeHose, decodeEndFitting } from './item.hose.decoder.js'

// Auto-generated codes are picked from a COUNT(*)-derived candidate (see
// itemModel.generateUniqueCode), so two concurrent importer calls can pick
// the same candidate before either commits. Retrying the insert with a
// freshly generated code resolves that race; a collision on a caller-
// supplied code is a real conflict and still fails immediately.
async function insertItemWithAutoCodeRetry(conn, params, wasAutoGenerated) {
  let current = params
  for (let attempt = 0; attempt < 20; attempt++) {
    try {
      const itemId = await itemModel.insertItem(conn, current)
      return { itemId, code: current.code }
    } catch (err) {
      if (wasAutoGenerated && err.code === 'ER_DUP_ENTRY' && attempt < 19) {
        current = { ...current, code: await itemModel.generateUniqueCode(conn) }
        continue
      }
      throw err
    }
  }
}

/**
 * Import one fitting row (code + description) into item / item_end /
 * item_attribute_value. code may be blank, in which case a unique code is
 * generated (D14) — the caller can edit it afterwards via updateItemCode.
 */
export async function importFittingItem({ code, description }) {
  const conn = await itemModel.pool.getConnection()
  try {
    await conn.beginTransaction()

    const fittingTypeOptions = await itemModel.fittingTypeOptionValues(conn)
    const decoded = decodeFitting({ code: code || null, description }, { fittingTypeOptions })

    const catId = await itemModel.categoryId(conn, decoded.category)
    const baseUomId = await itemModel.uomId(conn, decoded.base_uom)
    const fittingTypeAttrId = await itemModel.attributeId(conn, 'fitting_type')
    const fittingTypeOptId = await itemModel.optionId(conn, fittingTypeAttrId, decoded.fitting_type)

    const wasAutoGenerated = !decoded.code
    const initialCode = decoded.code || (await itemModel.generateUniqueCode(conn))

    const { itemId, code: finalCode } = await insertItemWithAutoCodeRetry(
      conn,
      {
        code: initialCode,
        name: decoded.name,
        categoryId: catId,
        baseUomId,
        status: decoded.status,
        procurementMode: decoded.procurement_mode,
      },
      wasAutoGenerated,
    )

    for (const end of decoded.ends) {
      await itemModel.insertItemEnd(conn, itemId, end)
    }

    await itemModel.insertItemAttributeOption(conn, itemId, fittingTypeAttrId, fittingTypeOptId)

    await conn.commit()
    return { itemId, code: finalCode, fittingType: decoded.fitting_type, ends: decoded.ends }
  } catch (err) {
    await conn.rollback()
    throw err
  } finally {
    conn.release()
  }
}

/**
 * Import one hose or hose-end-fitting row. Hoses get no ends (raw hose
 * isn't terminated); end-fittings get exactly one hose end + one
 * connection end. code may be blank (D14 auto-generation, same as fittings).
 */
export async function importHoseOrEndFittingItem({ kind, code, description }) {
  const conn = await itemModel.pool.getConnection()
  try {
    await conn.beginTransaction()

    let decoded
    if (kind === 'hose') {
      const refs = {
        brandOptions: await itemModel.optionValues(conn, 'brand'),
        seriesOptions: await itemModel.optionValues(conn, 'series'),
        hoseStandardOptions: await itemModel.optionValues(conn, 'hose_standard'),
        hoseConstructionOptions: await itemModel.optionValues(conn, 'hose_construction'),
      }
      decoded = decodeHose({ code: code || null, description }, refs)
    } else if (kind === 'endfitting') {
      decoded = decodeEndFitting({ code: code || null, description })
    } else {
      throw new Error(`unknown item kind: ${kind}`)
    }

    const catId = await itemModel.categoryId(conn, decoded.category)
    const baseUomId = await itemModel.uomId(conn, decoded.base_uom)
    const materialId = await itemModel.materialId(conn, decoded.material)
    const wasAutoGenerated = !decoded.code
    const initialCode = decoded.code || (await itemModel.generateUniqueCode(conn))

    const { itemId, code: finalCode } = await insertItemWithAutoCodeRetry(
      conn,
      {
        code: initialCode,
        name: decoded.name,
        categoryId: catId,
        baseUomId,
        status: decoded.status,
        procurementMode: 'in_app',
        materialId,
        isManufacturable: decoded.isManufacturable,
      },
      wasAutoGenerated,
    )

    for (const end of decoded.ends) {
      const toInsert = { ...end }
      if (toInsert.inch) {
        toInsert.size_dash = await itemModel.dashForInch(conn, `${toInsert.inch}"`)
        delete toInsert.inch
      }
      await itemModel.insertItemEnd(conn, itemId, toInsert)
    }

    for (const attr of decoded.attributes) {
      const attrId = await itemModel.attributeId(conn, attr.code)
      if (attr.type === 'option') {
        const optId = await itemModel.optionId(conn, attrId, attr.value)
        await itemModel.insertItemAttributeOption(conn, itemId, attrId, optId)
      } else {
        let value = attr.value
        if (value == null && attr.inch) value = await itemModel.dashForInch(conn, `${attr.inch}"`)
        await itemModel.insertItemAttributeNumber(conn, itemId, attrId, value)
      }
    }

    await conn.commit()
    return { itemId, code: finalCode, kind: decoded.kind }
  } catch (err) {
    await conn.rollback()
    throw err
  } finally {
    conn.release()
  }
}

export async function updateItemCode(itemId, newCode) {
  const conn = await itemModel.pool.getConnection()
  try {
    await itemModel.updateItemCode(conn, itemId, newCode)
  } finally {
    conn.release()
  }
}
